In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4]

In [3]:
my_array1 = np.array(my_list1)

In [4]:
my_array1

array([1, 2, 3, 4])

In [5]:
my_list2 = [11,22,33,44]

In [6]:
my_lists = [my_list1, my_list2]

In [7]:
my_array2 = np.array(my_lists)

In [8]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [9]:
my_array2.shape

(2L, 4L)

In [10]:
my_array2.dtype

dtype('int32')

In [11]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [12]:
my_zeros_array = np.zeros(5)
my_zeros_array.dtype

dtype('float64')

In [13]:
np.ones([5.5])

array([ 1.,  1.,  1.,  1.,  1.])

In [14]:
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [15]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [16]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [19]:
my_list

NameError: name 'my_list' is not defined

In [20]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [21]:
my_list3 = [13,14]

In [22]:
my_lists = my_lists + my_list3

In [23]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44], 13, 14]

In [24]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [25]:
my_array3 = np.array(my_list3)

In [26]:
my_array3

array([13, 14])

In [27]:
my_array3 = np.array(my_lists)

In [28]:
my_array3

array([[1, 2, 3, 4], [11, 22, 33, 44], 13, 14], dtype=object)

In [29]:
np.my_array3.shape

AttributeError: 'module' object has no attribute 'my_array3'

In [30]:
my_array3.shape

(4L,)

In [31]:
my_array3.dtype

dtype('O')

In [34]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [35]:
np.zeros(100)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [36]:
np.ones(2,5)

TypeError: data type not understood

In [40]:
np.zeros((5,2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])